In [2]:
import numpy as np
import scipy.sparse as ss

In [11]:
def connected_adjacency(image, connect=8, patch_size=(1, 1)):
    """
    Construct 8-connected pixels base graph (0 for not connected, 1 for connected)
    """
    r, c = image.shape[:2]
    r = int(r / patch_size[0])
    c = int(c / patch_size[1])

    if connect == "4":
        # constructed from 2 diagonals above the main diagonal
        d1 = np.tile(np.append(np.ones(c - 1), [0]), r)[:-1]
        # print(d1.shape)
        
        d2 = np.ones(c * (r - 1))
        # print(d2.shape)
        upper_diags = ss.diags([d1, d2], [1, c])
        # print(upper_diags.shape)
        # print(upper_diags.T.shape)
        # print((upper_diags + upper_diags.T).shape)
        return upper_diags + upper_diags.T
width = 3
pixel_indices = [i for i in range(width * width)]
pixel_indices = np.reshape(pixel_indices, (width, width))
A = connected_adjacency(pixel_indices,"4",(1,1))
A_pair = np.asarray(np.where(A.toarray() == 1)).T
print(type(A_pair))
print(A_pair.shape)
# print(np.sort(A_pair, axis=1))
A_pair = np.unique(np.sort(A_pair, axis=1), axis=0)
# print(A_pair)
# print(A_pair.shape)
# print(type(A_pair))
edges = A_pair.shape[0]
H_dim0 = edges
H_dim1 = width ** 2




<class 'numpy.ndarray'>
(24, 2)


In [8]:
from PIL import Image
import cv2
import numpy as np
import torch
img = np.array(Image.open("deepgtv\legacy\diff_stat.png"))
print(img.shape)
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img.shape)
img = np.expand_dims(img, axis=2)
print(img.shape)


(395, 687, 4)
(395, 687)
(395, 687, 1)


In [17]:
import scipy.sparse as ss
import numpy as np

# Tạo danh sách đường chéo và vị trí của chúng
diagonals = [np.array([1, 2, 3]), np.array([4, 5, 6])]
offsets = [1, 2]

# Sử dụng ss.diags để tạo ma trận thưa
sparse_matrix = ss.diags(diagonals, offsets)

# In ma trận thưa
print(sparse_matrix)


  (0, 1)	1.0
  (1, 2)	2.0
  (2, 3)	3.0
  (0, 2)	4.0
  (1, 3)	5.0


In [52]:
import numpy as np

# Tạo một mảng NumPy hai chiều
arr = np.array([[1, 2, 2, 3], [4, 5, 6, 4], [7, 8, 9, 7]])

# Sử dụng np.unique() để tìm các giá trị duy nhất trên toàn mảng
unique_values = np.unique(arr)

print(unique_values)
print()
unique_values_axis0 = np.unique(arr, axis=0)

print(unique_values_axis0)
print()
unique_values_axis1 = np.unique(arr, axis=1)

print(unique_values_axis1)



[1 2 3 4 5 6 7 8 9]

[[1 2 2 3]
 [4 5 6 4]
 [7 8 9 7]]

[[1 2 2 3]
 [4 5 6 4]
 [7 8 9 7]]


In [27]:
import torch

# Tạo một tensor
x = torch.tensor([-10])

# Thêm một chiều có kích thước 1 vào tensor
y = x.unsqueeze(1).unsqueeze(1)
y = torch.clamp(y, 0, 50)
print(y)
print(y.shape)


tensor([[[0]]])
torch.Size([1, 1, 1])


In [4]:
import os

folder_path = "C:/Users/efe/OneDrive/Desktop/dicom_data_zip/DICOM/ST00001/SE00001"

# Duyệt qua tất cả các file trong thư mục
for filename in os.listdir(folder_path):
    # Tạo đường dẫn tuyệt đối đầy đủ cho mỗi file
    filepath = os.path.join(folder_path, filename)

    # Nếu là file (không phải thư mục)
    if os.path.isfile(filepath):
        # Tạo tên mới với định dạng .dicom
        new_filename = os.path.splitext(filename)[0] + ".dicom"

        # Tạo đường dẫn mới cho file
        new_filepath = os.path.join(folder_path, new_filename)

        # Đổi tên file
        os.rename(filepath, new_filepath)

print("Đã đổi tên các file thành công.")

Đã đổi tên các file thành công.
