In [4]:
import numpy as np
import scipy.sparse as ss

In [5]:
def connected_adjacency(image, connect=8, patch_size=(1, 1)):
    """
    Construct 8-connected pixels base graph (0 for not connected, 1 for connected)
    """
    r, c = image.shape[:2]
    r = int(r / patch_size[0])
    c = int(c / patch_size[1])

    if connect == "4":
        # constructed from 2 diagonals above the main diagonal
        d1 = np.tile(np.append(np.ones(c - 1), [0]), r)[:-1]
        print(d1)
        
        print(d1.shape)
        
        d2 = np.ones(c * (r - 1))
        print(d2)
        
        print(d2.shape)
        
        upper_diags = ss.diags([d1, d2], [1, c])
        print(upper_diags)
        
        print(upper_diags.shape)
        
        print(upper_diags + upper_diags.T)
        
        return upper_diags + upper_diags.T
width = 3
pixel_indices = [i for i in range(width * width)]
pixel_indices = np.reshape(pixel_indices, (width, width))
A = connected_adjacency(pixel_indices,"4",(1,1))
A_pair = np.asarray(np.where(A.toarray() == 1)).T
A_pair = np.unique(np.sort(A_pair, axis=1), axis=0)
print(A_pair)
print(A_pair.shape)


[1. 1. 0. 1. 1. 0. 1. 1.]
(8,)
[1. 1. 1. 1. 1. 1.]
(6,)
  (0, 1)	1.0
  (1, 2)	1.0
  (3, 4)	1.0
  (4, 5)	1.0
  (6, 7)	1.0
  (7, 8)	1.0
  (0, 3)	1.0
  (1, 4)	1.0
  (2, 5)	1.0
  (3, 6)	1.0
  (4, 7)	1.0
  (5, 8)	1.0
(9, 9)
  (0, 1)	1.0
  (1, 2)	1.0
  (3, 4)	1.0
  (4, 5)	1.0
  (6, 7)	1.0
  (7, 8)	1.0
  (0, 3)	1.0
  (1, 4)	1.0
  (2, 5)	1.0
  (3, 6)	1.0
  (4, 7)	1.0
  (5, 8)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (4, 3)	1.0
  (5, 4)	1.0
  (7, 6)	1.0
  (8, 7)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 2)	1.0
  (6, 3)	1.0
  (7, 4)	1.0
  (8, 5)	1.0
[[0 1]
 [0 3]
 [1 2]
 [1 4]
 [2 5]
 [3 4]
 [3 6]
 [4 5]
 [4 7]
 [5 8]
 [6 7]
 [7 8]]
(12, 2)


In [6]:
from PIL import Image
import cv2
import numpy as np
import torch
img = np.array(Image.open("deepgtv\legacy\diff_stat.png"))
print(img.shape)
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img.shape)
img = np.expand_dims(img, axis=2)
print(img.shape)


(395, 687, 4)
(395, 687)
(395, 687, 1)
