In [1]:
import numpy as np
import scipy.sparse as ss

In [57]:
def connected_adjacency(image, connect=8, patch_size=(1, 1)):
    """
    Construct 8-connected pixels base graph (0 for not connected, 1 for connected)
    """
    r, c = image.shape[:2]
    r = int(r / patch_size[0])
    c = int(c / patch_size[1])

    if connect == "4":
        # constructed from 2 diagonals above the main diagonal
        d1 = np.tile(np.append(np.ones(c - 1), [0]), r)[:-1]
        print(d1.shape)
        
        d2 = np.ones(c * (r - 1))
        print(d2.shape)
        upper_diags = ss.diags([d1, d2], [1, c])
        print(upper_diags.shape)
        print(upper_diags.T.shape)
        print((upper_diags + upper_diags.T).shape)
        return upper_diags + upper_diags.T
width = 3
pixel_indices = [i for i in range(width * width)]
pixel_indices = np.reshape(pixel_indices, (width, width))
A = connected_adjacency(pixel_indices,"4",(1,1))
A_pair = np.asarray(np.where(A.toarray() == 1)).T
print(A_pair)
print(A_pair.shape)
print(np.sort(A_pair, axis=1))
A_pair = np.unique(np.sort(A_pair, axis=1), axis=0)
print(A_pair)
print(A_pair.shape)
print(type(A_pair))
edges = A_pair.shape[0]
H_dim0 = edges
H_dim1 = width ** 2
H = np.zeros(12, 9).type(float)
print(H)
print()
print(H.shape)



(8,)
(6,)
(9, 9)
(9, 9)
(9, 9)
[[0 1]
 [0 3]
 [1 0]
 [1 2]
 [1 4]
 [2 1]
 [2 5]
 [3 0]
 [3 4]
 [3 6]
 [4 1]
 [4 3]
 [4 5]
 [4 7]
 [5 2]
 [5 4]
 [5 8]
 [6 3]
 [6 7]
 [7 4]
 [7 6]
 [7 8]
 [8 5]
 [8 7]]
(24, 2)
[[0 1]
 [0 3]
 [0 1]
 [1 2]
 [1 4]
 [1 2]
 [2 5]
 [0 3]
 [3 4]
 [3 6]
 [1 4]
 [3 4]
 [4 5]
 [4 7]
 [2 5]
 [4 5]
 [5 8]
 [3 6]
 [6 7]
 [4 7]
 [6 7]
 [7 8]
 [5 8]
 [7 8]]
[[0 1]
 [0 3]
 [1 2]
 [1 4]
 [2 5]
 [3 4]
 [3 6]
 [4 5]
 [4 7]
 [5 8]
 [6 7]
 [7 8]]
(12, 2)
<class 'numpy.ndarray'>


TypeError: Cannot interpret '9' as a data type

In [8]:
from PIL import Image
import cv2
import numpy as np
import torch
img = np.array(Image.open("deepgtv\legacy\diff_stat.png"))
print(img.shape)
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img.shape)
img = np.expand_dims(img, axis=2)
print(img.shape)


(395, 687, 4)
(395, 687)
(395, 687, 1)


In [17]:
import scipy.sparse as ss
import numpy as np

# Tạo danh sách đường chéo và vị trí của chúng
diagonals = [np.array([1, 2, 3]), np.array([4, 5, 6])]
offsets = [1, 2]

# Sử dụng ss.diags để tạo ma trận thưa
sparse_matrix = ss.diags(diagonals, offsets)

# In ma trận thưa
print(sparse_matrix)


  (0, 1)	1.0
  (1, 2)	2.0
  (2, 3)	3.0
  (0, 2)	4.0
  (1, 3)	5.0


In [52]:
import numpy as np

# Tạo một mảng NumPy hai chiều
arr = np.array([[1, 2, 2, 3], [4, 5, 6, 4], [7, 8, 9, 7]])

# Sử dụng np.unique() để tìm các giá trị duy nhất trên toàn mảng
unique_values = np.unique(arr)

print(unique_values)
print()
unique_values_axis0 = np.unique(arr, axis=0)

print(unique_values_axis0)
print()
unique_values_axis1 = np.unique(arr, axis=1)

print(unique_values_axis1)



[1 2 3 4 5 6 7 8 9]

[[1 2 2 3]
 [4 5 6 4]
 [7 8 9 7]]

[[1 2 2 3]
 [4 5 6 4]
 [7 8 9 7]]


In [27]:
import torch

# Tạo một tensor
x = torch.tensor([-10])

# Thêm một chiều có kích thước 1 vào tensor
y = x.unsqueeze(1).unsqueeze(1)
y = torch.clamp(y, 0, 50)
print(y)
print(y.shape)


tensor([[[0]]])
torch.Size([1, 1, 1])
